### ISSUE TITLE
Error when teleporting

### ISSUE THREAD

**Issue by xickle** [oneill011990/FastTravelReborn#7]
`
19:58:35 [ERROR] Could not pass event FastTravelEvent to FastTravelSigns v1.0.4
19:58:35 org.bukkit.event.EventException
19:58:35 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
19:58:35 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
19:58:35 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
19:58:35 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
19:58:35 at de.germanspacebuild.plugins.fasttravel.menu.SignMenu.travel(SignMenu.java:194) [FastTravelReborn-1.0.5.jar:?]
19:58:35 at de.germanspacebuild.plugins.fasttravel.Listener.FTInventoryListener.onInventoryClick(FTInventoryListener.java:69) [FastTravelReborn-1.0.5.jar:?]
19:58:35 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
19:58:35 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
19:58:35 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
19:58:35 at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
19:58:35 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
19:58:35 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
19:58:35 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
19:58:35 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
19:58:35 at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1837) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
19:58:35 at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
19:58:35 at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
19:58:35 at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
19:58:35 at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_102]
19:58:35 at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_102]
19:58:35 at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
19:58:35 at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
19:58:35 at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
19:58:35 at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
19:58:35 at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
19:58:35 at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]
19:58:35 Caused by: java.lang.NullPointerException
19:58:35 at de.germanspacebuild.plugins.fasttravel.io.Translator.getKey(Translator.java:93) ~[?:?]
19:58:35 at de.germanspacebuild.plugins.fasttravel.io.IOManager.translate(IOManager.java:77) ~[?:?]
19:58:35 at de.germanspacebuild.plugins.fasttravel.io.IOManager.sendTranslation(IOManager.java:73) ~[?:?]
19:58:35 at de.germanspacebuild.plugins.fasttravel.Listener.FTTravelListener.onFastTravel(FTTravelListener.java:78) ~[?:?]
19:58:35 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
19:58:35 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
19:58:35 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
19:58:35 at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
19:58:35 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
19:58:35 ... 25 more
`
I have enabled Economy(using Vault) and added a cost(5), warmup(15) and cooldown(60) in the config. This error occured to me when trying to teleport from the menu. It did not end up teleporting me.

Using FastTravelReborn 1.0.5 (even though error mentions 1.0.4)
Spigot 1.11

**Comment by oneill011990** [comment]
I missed the E-Mail about this for some reason, sorry about that. I think it is fixed in the upcoming 1.0.6
